дз
MamedovaEsmira/Course_Work_3_sock-shop pull request #1
Opened 2023-02-14 18:55 UTC by MamedovaEsmira

2023-02-16 17:44 UTC, alekseykoshelev requested changes

2023-02-16 17:44 UTC, alekseykoshelev commented on src/main/java/com/example/sockshop/controllers/SockShopController.java
> +        public ResponseEntity<Object> getSocks(@PathVariable Color color,
Тут это нужно сделать как request param. Из пути в запросе тоже нужно убрать.

2023-02-16 17:44 UTC, alekseykoshelev commented on src/main/java/com/example/sockshop/service/impl/SockShopServiceImpl.java
> +        public Set<Socks> socksSet = new LinkedHashSet<>();
Лучше модификатор сделать private

2023-02-16 17:44 UTC, alekseykoshelev commented on src/main/java/com/example/sockshop/service/impl/SockShopServiceImpl.java
> +                    socks1.setQuantity(socks1.getQuantity() + socks.getQuantity());
Не совсем верная логика, тут ты к каждым носкам прибавляешь количество. Нужно прибавлять именно к тем, которые совпадают по параметрам.

2023-02-20 20:03 UTC, alekseykoshelev requested changes

2023-02-20 20:03 UTC, alekseykoshelev commented on src/main/java/com/example/sockshop/service/impl/SockShopServiceImpl.java
> +                    socks.setQuantity(socks.getQuantity() + socks.getQuantity());
Тут нужно найти такие носки в коллекции и поменять у них количество. Сейчас количество меняется у аргумента, что бессмысленно.

2023-02-20 20:03 UTC, alekseykoshelev commented on src/main/java/com/example/sockshop/controllers/SockShopController.java
> +                                               int cottonMin,
Тут тоже нужно добавить RequestParam, а также поменять путь у этого эндпоинта. Там не нужны теперь аргументы в пути.

2023-02-21 09:33 UTC, MamedovaEsmira commented on src/main/java/com/example/sockshop/service/impl/SockShopServiceImpl.java
> +                    socks.setQuantity(socks.getQuantity() + socks.getQuantity());
погодите, я не поняла, тут же я добавляю носки, а не меняю количество, я короче вообще запуталась

2023-02-21 20:19 UTC, merged